apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://helm.open-metadata.org/
      targetRevision: "1.10.8"
      chart: openmetadata
      helm:
        valueFiles:
          - $values/k8s/openmetadata/helm/values.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openmetadata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
