# https://containers.dev/guide/dockerfile
name: devcontainer

include:
  - compose-core.yaml
  - compose-lakehouse.yaml
  - compose-processing.yaml
  - compose-notebooks.yaml
  - compose-streaming.yaml

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN

volumes:
  debezium-postgres-config:
  airflow-2-11-data:
  flink-state:
  hive-metastore-data:
  hive-postgres-config:
  airflow-data:
  kafka-data:
  postgres-data:
  seaweedfs-data:
  ssh-tunnel-config:
  superset-data:

# https://docs.docker.com/compose/how-tos/networking/
networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  external:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  backend:
    internal: true   # No external connectivity
  tunnel:
    internal: true   # No external connectivity
