apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-go-app-3
  template:
    metadata:
      labels:
        app: sample-go-app-3
    spec:
      containers:
        - name: sample-go-3
          image: local/sample-go-app-3:4830709
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
