name: dbt_pyspark_demo
version: "1.0.0"
config-version: 2

profile: dbt_pyspark_demo

model-paths:
  - models

clean-targets:
  - target
  - dbt_packages

models:
  dbt_pyspark_demo:
    staging:
      +materialized: view

    marts:
      +materialized: table
      