apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-all
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git 
    targetRevision: HEAD
    path: k8s/airflow/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
