apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino-helm
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://trinodb.github.io/charts/
      chart: trino
      targetRevision: "1.39.1"
      helm:
        valueFiles:
          - $values/k8s/trino/helm/values.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: trino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
