apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-nfs-driver
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      targetRevision: "4.11.0"
      chart: csi-driver-nfs
      helm:
        valueFiles:
          - $values/k8s/csi-driver-nfs/helm/values-pvel.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true