apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://mysql.github.io/mysql-operator/
    targetRevision: 2.2.6
    chart: mysql-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: innodbclusters.mysql.oracle.com
      jqPathExpressions:
        - .spec.versions[].schema.openAPIV3Schema.properties.endpoints.description