apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-nfs-git-zeppelin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi-git-zeppelin
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: vm.worldl1.worldl.xpt/test##
    volumeAttributes:
      server: vm.pve.worldl.xpt
      share: /mnt/data/git
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-git
spec:
  accessModes:
    - ReadWriteMany # Must match the accessModes of the PV
  storageClassName: nfs-csi-git-zeppelin # Must match the storageClassName of the PV
  resources:
    requests:
      storage: 10Gi # Must be less than or equal to the PV's capacity