apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub-kustomize
  namespace: argo-cd
  annotations:
    # Wait app-kafka-bootstrap.yaml. Wait until the project exists
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
    targetRevision: HEAD
    path: k8s/datahub/kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: datahub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
