# Single-node development configuration
coordinator=true
node-scheduler.include-coordinator=true
discovery.uri=http://localhost:8080
catalog.management=${ENV:CATALOG_MANAGEMENT}

# Traefik adds X-Forwarded-* headers to proxied requests.
http-server.process-forwarded=true
