apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-s3
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Namespace
metadata:
  name: rustfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvel-vm-s3
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-s3
  claimRef:
    namespace: rustfs
    name: rustfs-data
  local:
    path: /data/s3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vm.pvel.worldl.xpt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-s3
  volumeName: pvel-vm-s3
  resources:
    requests:
      storage: 400Gi
