apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-extra
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rogeriomm/monorepo-datahub-ops.git
    path: k8s/airflow/extra
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  info:
    - name: wave
      value: "1"
