FROM apache/airflow:3.3.0

RUN pip install --no-cache-dir \
    "apache-airflow==3.3.0" \
    "apache-airflow-providers-postgres==6.8.0" \
    "apache-airflow-providers-mysql" \
    "apache-airflow-providers-snowflake" \
    "apache-airflow-providers-amazon" \
    "apache-airflow-providers-cncf-kubernetes" \
    "apache-airflow-providers-dbt-cloud"
