apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-crds
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://helm.mariadb.com/mariadb-operator
    targetRevision: 25.10.2
    chart: mariadb-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
