---
apiVersion: v1
kind: Pod
metadata:
  name: pv-debug-pod
spec:
  containers:
  - name: debug-container
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: nfs-storage
      mountPath: /mnt/data/git # Mount the PVC here
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: pvc-nfs-git # Reference the PVC by its name
