sink.retry.max_attempt=10
sink.retry.delay_ms=100
sink.retry.max_delay_ms=30000
sink.writer.num_concurrent_file=128
table.thread_pool_size=4
table.cache.enable=true
table.cache.size=200
table.cache.expire_ms=300000
