kafka:
  clusters:
    - name: local
      bootstrapServers: PLAINTEXT://my-kafka-bootstrap.kafka.svc.cluster.local:9092

resources:
  {}
  # limits:
  #   cpu: 200m
  #   memory: 512Mi
  # requests:
#   cpu: 200m
#   memory: 256Mi

# Ingress configuration
ingress:
  # Enable ingress resource
  enabled: false

  # Annotations for the Ingress
  annotations:
    cert-manager.io/cluster-issuer: spnw-intermediate-ca1-issuer
    cert-manager.io/common-name: "kafkaui.vm.world1l.worldl.xpt"

  # ingressClassName for the Ingress
  ingressClassName: "nginx"

  # The path for the Ingress
  path: "/"

  # The path type for the Ingress
  pathType: "Prefix"

  # The hostname for the Ingress
  host: "kafkaui.vm.world1l.worldl.xpt"

  # configs for Ingress TLS
  tls:
    # Enable TLS termination for the Ingress
    enabled: true
    # the name of a pre-created Secret containing a TLS private key and certificate
    secretName: "kafkaui-cert-secret"

  # HTTP paths to add to the Ingress before the default path
  precedingPaths: []

  # Http paths to add to the Ingress after the default path
  succeedingPaths: []
