# https://containers.dev/guide/dockerfile
services:
  tools:
    build:
      context: swiss-knife-tools
      dockerfile: Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
        DOCKER_GID: 960
        GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
      secrets:
        - GITHUB_TOKEN
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_REGION=${AWS_REGION:-}
    container_name: tool
    restart: unless-stopped
    security_opt:
      - label=disable
    ports:
      # Java debug port
      - "5005:5005"
      #  JupyterLab
      - "9001:8001"
      # Apache Zeppelin
      - "9002:8002"
      # SSH server
      - "9022:22"
    # mount a local directory
    volumes:
      - ../..:/workspaces:cached
      - $HOME/data:/data:z
      # SSH configuration
      - $HOME/.ssh:/home/ubuntu/.ssh:z
      # Maven cache, Spark build
      - $HOME/.m2:/home/ubuntu/.m2:z
      # mise cache
      - $HOME/.local/share/mise:/home/ubuntu/.local/share/mise:z
      # TMUX configuration
      - $HOME/.tmux.conf:/home/ubuntu/.tmux.conf:z
      - $HOME/.tmux:/home/ubuntu/.tmux:z
      # Dot config directory
      - $HOME/.config:/home/ubuntu/.config:z
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # JetBrains crack
      - /opt/jetbrains/agent.jar:/opt/jetbrains/agent.jar:ro
    networks:
      - frontend
      - backend

  jupyter-spark-3.5:
    build:
      context: jupyter_spark_3_5
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_REGION=${AWS_REGION:-}
    container_name: jupyter_spark_3_5
    profiles:
      - jupyter_spark_3_5
    restart: unless-stopped
    security_opt:
      - label=disable
    ports:
      - "${JUPYTER_SPARK_3_5_PORT:-6660}:8888"
    command: start.sh jupyter notebook --NotebookApp.token=''
    volumes:
      - ../notebooks/jupyter:/home/jovyan
    networks:
      - frontend

  jupyter-spark-4.1:
    build:
      context: jupyter_spark_4_1
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_REGION=${AWS_REGION:-}
    container_name: jupyter_spark_4_1
    profiles:
      - jupyter_spark_4_1
    restart: unless-stopped
    security_opt:
      - label=disable
    ports:
      - "${JUPYTER_SPARK_4_1_PORT:-6660}:8888"
    command: start.sh jupyter notebook --NotebookApp.token=''
    volumes:
      - ../notebooks/jupyter:/home/jovyan
      - ../notebooks/jupyter:/home/jovyan/.
    networks:
      - frontend

  jupyter-glue-5:
    build:
      context: jupyter_spark_glue_5
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_REGION=${AWS_REGION:-}
    profiles:
      - jupyter_spark_glue_5
    restart: unless-stopped
    security_opt:
      - label=disable
    ports:
      - "${JUPYTER_GLUE_5_PORT:-6663}:8888"
    networks:
      - frontend

  # https://zeppelin.apache.org/docs/0.12.1/quickstart/docker.html
  zeppelin:
    build:
      context: ./zeppelin
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
    container_name: zeppelin
    profiles:
      - zeppelin
    restart: unless-stopped
    security_opt:
      - label=disable
    ports:
      - "${ZEPPELIN_PORT:-6661}:8080"
    volumes:
      - ../notebooks/zeppelin:/notebooks
    networks:
      - frontend

  # https://docs.localstack.cloud/aws/getting-started/installation/
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    profiles:
      - localstack
    image: localstack/localstack-pro # required for Pro
    #ports:
      #- '127.0.0.1:4566:4566' # LocalStack Gateway
      #- '127.0.0.1:4510-4559:4510-4559' # external services port range
      #- '127.0.0.1:443:443' # LocalStack HTTPS Gateway (Pro)
    environment:
      # Activate LocalStack for AWS: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?} # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - frontend

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN

# https://docs.docker.com/compose/how-tos/networking/
networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  backend:
    internal: true   # No external connectivity