# https://containers.dev/guide/dockerfile
services:
  tools:
    build:
      context: ./tools
      dockerfile: Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
        DOCKER_GID: 960
        GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
      secrets:
        - GITHUB_TOKEN
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
    container_name: tool
    restart: unless-stopped
    security_opt:
      - label=disable
    ports:
      # Java debug port
      - "5005:5005"
      #  JupyterLab
      - "9001:8001"
      # Apache Zeppelin
      - "9002:8002"
      # SSH server
      - "9022:22"
    # mount a local directory
    volumes:
      - ../..:/workspaces:cached
      - $HOME/data:/data:z
      # SSH configuration
      - $HOME/.ssh:/home/ubuntu/.ssh:z
      # Maven cache, Spark build
      - $HOME/.m2:/home/ubuntu/.m2:z
      # TMUX configuration
      - $HOME/.tmux.conf:/home/ubuntu/.tmux.conf:z
      - $HOME/.tmux:/home/ubuntu/.tmux:z
      # Dot config directory
      - $HOME/.config:/home/ubuntu/.config:z
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Jetbrains crack
      - /opt/jetbrains/agent.jar:/opt/jetbrains/agent.jar:ro

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    restart: unless-stopped
    security_opt:
      - label=disable
    ports:
      - "6660:8888"
    command: start.sh jupyter notebook --NotebookApp.token=''
    volumes:
      - ../notebooks/jupyter:/home/jovyan:cached

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
