apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-go-app-4
  template:
    metadata:
      labels:
        app: sample-go-app-4
    spec:
      containers:
        - name: sample-go-4
          image: local/sample-go-app-4:4830709
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
