apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-go-app-4
  template:
    metadata:
      labels:
        app: sample-go-app-4
    spec:
      containers:
        - name: sample-go-4
          image: harbor.ing.vm.pvel.worldl.xpt/main/sample-go-app-4:0.44
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
