apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.26.1
      helm:
        valueFiles:
          - $values/k8s/postgres/values.yaml
          - $values/k8s/postgres/values-pve.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: poolers.postgresql.cnpg.io
      jsonPointers:
        - /metadata/annotations/helm.sh~1resource-policy