apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-go-app-2
  template:
    metadata:
      labels:
        app: sample-go-app-2
    spec:
      containers:
        - name: sample-go-2
          image: local/sample-go-app-2:4830709
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
