apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-helm
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: mysql
      targetRevision: 13.0.0
      helm:
        valueFiles:
          - $values/k8s/mysql/helm/values.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true