image:
  repository: ghcr.io/gethomepage/homepage
  # tag: v0.6.0

# Enable RBAC. RBAC is necessary to use Kubernetes integration
enableRbac: true

extraClusterRoles:
# - apiGroups:
#   - some-group
#   resources:
#   - some-resource
#   verbs:
#   - get

serviceAccount:
  # Specify a different service account name. When blank it will default to the release
  # name if *create* is enabled, otherwise it will refer to the default service account.
  name: ""
  # Create service account. Needed when RBAC is enabled.
  create: true

service:
  main:
    ports:
      http:
        port: 3000

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

# All the config files for Homepage can be specified under their relevant config block.
config:
  # To use an existing ConfigMap uncomment this line and specify the name
  # useExistingConfigMap: existing-homepage-configmap
  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              icon: sh-github
              href: https://github.com/

        - Github monorepo-datahub-ops:
            - href: https://github.com/rogeriomm/monorepo-datahub-ops/actions
              icon: sh-github

        - Confluence:
            - abbr: CF
              icon: si-confluence
              href: https://rogermm.atlassian.net/wiki/home

        - ChapGPT:
            - abbr: CG
              href: https://chatgpt.com/?model=gpt-4o

        - Cloudflare:
            - abbr: CF
              icon: si-cloudflare
              href: https://dash.cloudflare.com/

        - Desec:
            - abbr: DS
              href: https://desec.io/domains

        - Check ports:
            - abbr: PR
              href: https://port.tools/port-checker-ipv6/

        - Godaddy:
           - abbr: GD
             href: https://dashboard.godaddy.com/

        - Libgen:
            - abbr: LG
              href:
                - https://libgen.gs/

        - Forcode:
            - abbr: FC
              href:
                - https://forcode.su/

    - Social:
        - Linkedin:
            - abbr: LN
              href: https://www.linkedin.com/feed/

  # https://gethomepage.dev/configs/services/#descriptions
  #   mdi-XX https://pictogrammers.com/library/mdi/
  #   si-XX https://simpleicons.org/
  #   sh-XX https://selfh.st/icons/
  services:
    - Lab:
       - world1l:
          - Homepage:
              href: https://worldl-homepage.worldb.site/
              icon: sh-homepage
          - Simple web:
              href: https://worldl-simple-web.worldb.site/
              siteMonitor: https://worldl-simple-web.worldb.site/
          - Zeppelin:
              href: https://worldl-zeppelin.worldb.site/
              icon: si-openzeppelin
              siteMonitor: https://worldl-zeppelin.worldb.site/
              description: Apache Zeppelin
          - ArgoCD:
              href: https://worldl-argocd.worldb.site/
              icon: si-argo
              siteMonitor: https://worldl-argocd.worldb.site/
          - Harbor:
              href: https://harbor.world1l.worldl.xpt/
              icon: si-harbor
              siteMonitor: https://harbor.world1l.worldl.xpt/

          - Prometheus:
              href: https://prometheus.vm.world1l.worldl.xpt/
              icon: si-prometheus
              siteMonitor: https://prometheus.vm.world1l.worldl.xpt/

          - Grafana:
              href: https://worldl-grafana.worldb.site/
              icon: si-grafana
              siteMonitor: https://worldl-grafana.worldb.site/
          - Kafka UI:
              href: https://worldl-kafkaui.worldb.site
              icon: si-apachekafka
              siteMonitor: https://worldl-kafkaui.worldb.site
          - Airflow:
              href: https://worldl-airflow.worldb.site
              icon: si-apacheairflow
              siteMonitor: https://worldl-airflow.worldb.site
          - Redpanda console:
              href: https://worldl-redpanda-console.worldb.site
              icon: sh-redmine
              siteMonitor: https://worldl-redpanda-console.worldb.site
       - pvel:
          - Homepage:
              href: https://pvel-homepage.worldb.site/
              icon: sh-homepage
          - Simple web:
              href: https://pvel-simple-web.worldb.site/
              siteMonitor: https://pvel-simple-web.worldb.site/
          - Proxmox:
              href: https://pvel.worldb.site/
              icon: si-proxmox
              description: Proxmox router N100
              siteMonitor: https://pvel.worldb.site/

          - Zeppelin:
              href: https://pvel-zeppelin.worldb.site/
              icon: si-openzeppelin
              description: Apache Zeppelin

          - Firewall:
              href: https://firewall.worldb.site/
              icon: si-opnsense
              description: OPNsense

          - Argocd:
             href: https://pvel-argocd.worldb.site/
             icon: si-argo
             siteMonitor: https://pvel-argocd.worldb.site/
             description: ArgoCD

          - Harbor:
              href: https://harbor.vm.pvel.worldl.xpt/
              icon: si-harbor
              siteMonitor: https://harbor.vm.pvel.worldl.xpt/

          - Prometheus:
              href: https://prometheus.vm.pvel.worldl.xpt/
              icon: si-prometheus
              siteMonitor: https://prometheus.vm.pvel.worldl.xpt/

          - Grafana:
              href: https://pvel-grafana.worldb.site/
              icon: si-grafana
              siteMonitor: https://pvel-grafana.worldb.site/
       - pve:
          - Simple web:
              href: https://pve-simple-web.worldb.site/
              siteMonitor: https://pve-simple-web.worldb.site/

          - pve:
              href: https://pve.worldb.site/
              icon: si-proxmox
              description: Proxmox XEON

          - truenas:
              href: https://truenas.worldb.site/
              icon: si-truenas
              description: TrueNAS

          - jellyfin:
              href: https://jellyfin.worldb.site/
              icon: si-jellyfin
              description: Jellyfin

          - transmission:
              href: https://transmission.worldb.site/
              icon: si-transmission
              description: Torrent

          - Argocd:
              href: https://pve-argocd.worldb.site/
              icon: si-argo
              siteMonitor: https://pve-argocd.worldb.site/
              description: ArgoCD

    - Sample applications:
      - Golang:
         - app-1:
             href: https://pvel-sample-go-app-1.worldb.site
         - app-2:
             href: https://pvel-sample-go-app-2.worldb.site
         - app-3:
             href: https://pvel-sample-go-app-3.worldb.site
         - app-4:
             href: https://pvel-sample-go-app-4.worldb.site
      - Rust:
         - app-1:
             href: https://pvel-sample-rust-app-1.worldb.site
         - app-2:
             href: https://pvel-sample-rust-app-2.worldb.site
         - app-3:
             href: https://pvel-sample-rust-app-3.worldb.site
         - app-4:
             href: https://pvel-sample-rust-app-4.worldb.site

  widgets:
    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    ## Uncomment to enable Kubernetes integration
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster

  docker:

  settings:

  # all sections can alternately be appended with "String" such as this example settings. This is useful
  # for defining a stable ordering. Unfortunately Go's (and therefore Helm's) toYaml function sorts keys
  # and loses and input ordering. Using a string is the best way around this.
  settingsString: |
    title: Homepage
    headerStyle: boxed
    layout:
      world1l:
      pvel:
      pve:

# To include environment variables from other configs or other secrets for use in
# Homepage's variable substitutions. Refer to them here.
# envFrom:
#   - secretRef:
#       name: my-secret
#   - configMapRef:
#       name: my-configmap

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs

# resources:
#   requests:
#     memory: 10Mi
#     cpu: 10m
#   limits:
#     memory: 200Mi
#     cpu: 500m
