apiVersion: v1
kind: Service
metadata:
  name: sample-go-app-1
  labels:
    app.kubernetes.io/name: sample-go-app-1
spec:
  selector:
    app: sample-go-app-1
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
