[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "squid-local"
version = "0.1.0"
requires-python = ">=3.12,<3.14"
dependencies = [
    "boto3>=1.40.0",
    "cryptography>=50.0.0",
    "databricks-sdk>=0.117.0",
    "dbt-core>=1.12.0",
    "humanize>=4.16.0",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
    "pandas>=3.0.5",
    "pandas-stubs~=3.0.5",
    "pip>=26.2.1",
    "psycopg2-binary>=2.9.12",
    "pyspark==4.1",
    "rich>=15.0.0",
    "trino>=0.339.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = [
    "squid",
    "squid.core*",
    "squid.on-premises*",
    "squid.resources*",
]

[tool.uv.workspace]
members = [
    "packages/squid-databricks",
    "packages/squid-on-premises",
]
