apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: kube-prometheus-stack
      targetRevision: 56.6.0
      helm:
        valueFiles:
          - $values/k8s/prometheus/values.yaml
          - $values/k8s/prometheus/values-pvel.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
