[fedora_atomic]
world1l ansible_host=world1l ansible_user=rogermm

[ubuntu]
pvel-vm    ansible_host=vm.pvel.worldl.xpt    ansible_user=rogermm
world1l-vm ansible_host=vm.world1l.worldl.xpt ansible_user=rogermm

[ubuntu:vars]
ansible_become=true
ansible_become_method=sudo
ansible_become_exe=/usr/bin/sudo.ws
ansible_python_interpreter=/usr/bin/python3.14

[proxmox]
pvel    ansible_host=pvel.worldl.xpt ansible_user=rogermm ansible_port=8007
pve     ansible_host=pve.worldl.xpt  ansible_user=rogermm ansible_port=8007

[proxmox:vars]
ansible_become=true
ansible_become_method=sudo
ansible_become_exe=/usr/bin/sudo
ansible_python_interpreter=/usr/bin/python3

[servers:children]
ubuntu
proxmox

[desktop:children]
fedora_atomic

