apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: kube-prometheus-stack
      targetRevision: 70.7.0
      helm:
        valueFiles:
          - $values/k8s/prometheus/values.yaml
          - $values/k8s/prometheus/values-pvel.yaml
    - repoURL: https://github.com/rogeriomm/monorepo-datahub-ops.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
