apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack-helm
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://localstack.github.io/helm-charts
      chart: localstack
      targetRevision: "0.6.24"
      helm:
        valueFiles:
          - $values/k8s/localstack/helm/values.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
