apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.19.2
      helm:
        valueFiles:
          - $values/on-premises/k8s/harbor/values.yaml
          - $values/on-premises/k8s/harbor/values-world1l.yaml
    - repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "" # Core Kubernetes API group
      kind: Secret
      name: harbor-ingress
      namespace: harbor
      jsonPointers:
        - /data