name: argocd

on:
  push:
    branches: [ "master" ]
    paths:
      - 'k8s/argocd/**'
      - '.github/workflows/argocd.yml'

jobs:
  deploy:
    runs-on: [ self-hosted ]

    steps:
      - name: Install
        run: |
          echo "Install"
      - uses: clowdhaus/argo-cd-action/@main
        env:
          # Only required for first step in job where API is called
          # All subsequent setps in a job will not re-download the CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: version
          options: --client -o json
      - uses: clowdhaus/argo-cd-action/@main
        # CLI has already been downloaded in prior step, no call to GitHub API
        with:
          command: version
          options: --client