apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-web
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:rogeriomm/monorepo-datahub-ops-private.git
    targetRevision: HEAD
    path: k8s/simple-web/overlays/world1l
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
